#!/bin/zsh

CACHE="${XDG_CACHE_HOME:-$HOME/.cache}"

calendar() {
    local lock="${CACHE}/eww-calendar.lock"

    if [[ ! -f "$lock" ]]; then
        # TODO: Close any/all other windows.
        touch "${lock}"
        eww open calendar
    else
        eww close calendar
        rm "${lock}"
    fi
}

if [[ "$1" = "calendar" ]]; then
    calendar
fi

