#! /bin/sh

picom -f&
dunst&
feh --bg-scale $HOME/wallpapers/levi.png --bg-scale $HOME/wallpapers/demonslayer.jpg
# $HOME/.config/eww/bar/launch_bar

pgrep -x sxhkd > /dev/null || sxhkd &

bspc wm --reorder-monitors DP-0 DP-2
bspc monitor ^1 -d 1 2 3 4 5
bspc monitor ^2 -d 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Floating Windows
bspc rule -a 'pinentry-qt' state=floating

bspc rule -a 'Alacritty' desktop='^1'
bspc rule -a 'Signal' desktop='^2'
bspc rule -a 'Google-chrome' desktop='^6'
bspc rule -a 'Microsoft Teams - Preview' desktop='^7'
