#!/bin/sh

status=$(nmcli g | grep -oE "disconnected")
essid=$(nmcli c | grep wlp5s0 | awk '{print ($1)}')
wired=$(nmcli c | grep enp6s0 | awk '{print ($1)}')

if [ $wired ] ; then
    icon=""
    text=${wired}
    col="#a1bdce"
else
    if [ $status ] ; then
        icon="睊"
        text="${essid}"
        col="#575268"

    else
        icon="直"
        text="${essid}"
        col="#a1bdce"
    fi
fi



if [[ "$1" == "--COL" ]]; then
    echo $col	
elif [[ "$1" == "--ESSID" ]]; then
	echo $text
elif [[ "$1" == "--ICON" ]]; then
	echo $icon
fi

